### PR TITLE
WIP: implement

### PR DESCRIPTION
**Pull request by kentcdodds**
Still working on this.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ping @aharris88, could you try this out?

```console
npm install prettier-eslint-cli@beta
./node_modules/.bin/prettier-eslint --help
```

Try it out on a project. I think that it's a solid start.

**Comment by kentcdodds** [comment]
Thinking it may be a good idea to add a `--write` option to actually override the files, otherwise it just prints out to `stdout`. This is what `prettier`'s CLI does. It's safer.

**Comment by edm00se** [comment]
I'm getting a replacement of my processed JS file contents with "undefined".

macOS Sierra (10.12.2)
Node: 6.9.1
npm: 3.10.1
(I normally run LTS latest, but apparently I'm behind a little)

Steps to reproduce:

- `git clone https://github.com/edm00se/personal-mock-url-shortener.git tmp`
- `cd tmp`
- `npm install`
- `npm install prettier-eslint-cli@beta -D`
- `./node_modules/.bin/prettier-eslint server.js`

The original source of the `server.js` file [can be found here](https://github.com/edm00se/personal-mock-url-shortener/blob/bc2d92d72233cdab0cf50b8e4082f3acf048c5fc/server.js).

Note: this will look slightly different [from my tweeted gif](https://twitter.com/edm00se/status/821770559117725696) as my initial test was against a local, un push-ed feature branch (changes were staged, it's all good 😉). I cloned a local copy from scratch as outlined in the steps above, got the same results ("undefined" replacing my file contents).

**Comment by aharris88** [comment]
Looks like it's working for me. 👍

**Comment by aharris88** [comment]
Although, I can't seem to get it to pick up my eslint config.

**Comment by kentcdodds** [comment]
That's good feedback @aharris88, could you dig into it a little bit?

**Comment by aharris88** [comment]
And this is what I have in my `.vimrc`

```
autocmd FileType javascript set formatprg=./node_modules/.bin/prettier-eslint\ --stdin
```

**Comment by aharris88** [comment]
Ok, I guess I had to reload vim. I'm not getting my file replaced with this:

```
success formatting 0 files with prettier-eslint ✨
```

**Comment by aharris88** [comment]
It works if I run it from the command line (and it's reading my `.eslintrc` file), but for some reason, when I run it in vim, it's not getting the file as input.

**Comment by kentcdodds** [comment]
`--stdin` isn't implemented (yet... I'm working on it now actually :smile:)

**Comment by kentcdodds** [comment]
@edm00se, I believe that [this](https://github.com/kentcdodds/prettier-eslint/commit/9129c8fe12f5e6f8e5b87fc68ccac50d001d68ce) should fix your issue. Could you clear your npm/yarn cache and try again?

**Comment by aharris88** [comment]
I actually just got the issue where it output `undefined`, and when I reinstalled, it fixed the issue.

**Comment by edm00se** [comment]
@kentcdodds This certainly fixes my updating to "undefined" in my files. I'm not sure that it's adhering to my eslint config, either in my `package.json` (initial) or in a (newly created) `.eslintrc` with the same contents.

eslint_formatting

**Comment by kentcdodds** [comment]
Yeah, that's probably `prettier` doing that :) Try pasting your code in [here](https://jlongster.github.io/prettier) and see what happens (note that the prettier config is generated via your eslint config, so you may need to adjust some things). But I think it's working!

**Comment by edm00se** [comment]
The output from pasting into that link looks pretty consistent, with the exception of that trailing comma.

**Comment by aharris88** [comment]
`print-width` is the option in prettier that is probably causing that multi-line issue. How do you set it with prettier-eslint-cli?

**Comment by kentcdodds** [comment]
The CLI doesn't expose any mechanism for customizing `prettier` currently (I don't think it'll be necessary). Instead, `prettier-eslint` will generate the `prettier` options based on the eslint config for the file it's formatting. The rule that it cares about is `max-len`

**Comment by kentcdodds** [comment]
@edm00se, I'm not certain about the trailing comma. 🤔 We should probably expose a way for you to log out the `eslintConfig` and `prettierOptions` that are used for the formatting. Would you be interested in doing that? Would probably just need another option (like `sillyLogs`) and add the `console.log` [here](https://github.com/kentcdodds/prettier-eslint/blob/master/src/index.js#L39) that includes the `eslintConfig` and `prettierOptions` (maybe put it in a separate function and just call it there... Wanna try?

**Comment by edm00se** [comment]
I'm game, but it'll probably have to be later in my day :'-( I can give it a try tonight at least.

**Comment by kentcdodds** [comment]
I'll file an issue you can use to reference.

**Comment by aharris88** [comment]
If you have invalid syntax, you get this error:

```
(node:98856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token, expected ) (202:9)
(node:98856) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kentcdodds** [comment]
Ah! Great point @aharris88! Thanks for that! I forgot to handle errors :)

**Comment by kentcdodds** [comment]
Alrighty! Could I get you guys to try `npm cache clean prettier-eslint-cli && npm install prettier-eslint-cli@beta && ./node_modules/.bin/prettier-eslint --version`

That should give you `1.0.0-beta.1`. If you could make sure that works for your stuff that'd be great! (@aharris88, there's now a `--stdin` option, and we handle errors gracefully).

Thanks for all the help and feedback!

**Comment by edm00se** [comment]
Uh... both `--help` and `--version` fail for me. `npm cache clean prettier-eslint-cli && npm install prettier-eslint-cli@beta` worked fine.

screenshot 2017-01-18 15 31 43

**Comment by kentcdodds** [comment]
Ran into a quick error and published a `1.0.0-beta.2` :)

**Comment by edm00se** [comment]
Runs clean now, reporting `1.0.0-beta.2`.

**Comment by kentcdodds** [comment]
Whoops, published it as `0.0.0-semantically-released` 😅 good things it's still `beta` :)

**Comment by kentcdodds** [comment]
Whoops! Forgot to add the `--write` flag. You have to specify that if you want it to update your files! Pushed out `1.0.0-beta.3` with that fix!

**Comment by kentcdodds** [comment]
Things are looking pretty good from my perspective. I'm finding a bunch of issues with `prettier` I think :)

**Comment by kentcdodds** [comment]
Will setup automatic releases tomorrow morning! Cheers!

**Pull request merged**
